name: PortMaster PR

on:
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure git
        run: |
           echo "machine github.com login ${{ secrets.GH_TOKEN }} password x-oauth-basic" >> ~/.netrc
           git config --global user.email "jaakko.lukkari@gmail.com"
           git config --global user.name "orktes"

      - name: Checkout PortMaster
        run: git clone --filter=blob:none --depth 1 --no-checkout https://github.com/PortsMaster/PortMaster-New.git PortMaster-New-Fork

      - name: Set to sparse checkout
        run: | 
          cd PortMaster-New-Fork
          git config core.sparseCheckout true
          echo "ports/maxpayne" >> .git/info/sparse-checkout
          git checkout main

      - name: Rebase from the original repo
        run: |
          cd PortMaster-New-Fork
          git remote add stage https://${{ secrets.GH_TOKEN }}@github.com/orktes/PortMaster-New.git

      - name: Remove Old Release
        run: |
          mkdir -p PortMaster-New-Fork/ports/maxpayne
          cd PortMaster-New-Fork/ports/maxpayne
          rm -Rf *

      - name: Download latest github release
        run: |
          cd PortMaster-New-Fork/ports/maxpayne
          curl -L -o maxpayne_arm64.zip https://github.com/orktes/max_r36s/releases/latest/download/maxpayne_arm64.zip
          unzip maxpayne_arm64.zip
          ls -lh
          rm maxpayne_arm64.zip

      - name: Commit
        run: |
          cd PortMaster-New-Fork
          git add .
          git commit -m "Update Max Payne port to $(head -1 PortMaster-New-Fork/ports/maxpayne/maxpayne/VERSION.txt)"

      - name: Push Changes
        run: |
          cd PortMaster-New-Fork
          git push stage main --force
